### PR TITLE
ADDS MORBPHINE (and also changes config to our defaults because i forgot to Not push that stuff)

### PR DESCRIPTION
**Pull request by brooje**
# Document the changes in your pull request

Adds Morbphine, a drug for Vampires. I have tested it, and it should be 100% funny.

# Changelog
:cl:  
rscadd: Added Morbphine!
/:cl:

### CODE REVIEW

**Comment by brooje** [comment]
morbius

**Comment by Kassete** [comment]
morbiSUS like if you agree

**Comment by Liberation546** [comment]
there are now No changes on this pr

**Comment by brooje** [comment]
#MORBIUSSWEEP

**Comment by Liberation546** [comment]
#MORBIUSSWEEP

**Comment by Liberation546** [comment]
0 of 3 checks passed

**Pull request merged**
